### ISSUE TITLE
C++ Integration

### ISSUE THREAD

**Issue by psilva98** [mapbox/geobuf#100]
Any plans on moving this to a C++ integration?

Wonderful tool, would be great to use on external data download, but in JS <Mobile> isn't happening.

**Comment by mourner** [comment]
I recall there's a Geobuf plugin for Mapnik written in C++, might be useful in this context — https://github.com/mapnik/mapnik/tree/master/plugins/input/geobuf

**Comment by district10** [comment]
I'm not aware of the mapnik geobuf plugin, here's my implementation: https://github.com/district10/geobuf-cpp

Hope this helpful for someone.
