### ISSUE TITLE
Unimplemented type 4

### ISSUE THREAD

**Issue by MyLittlePlan** [mapbox/geobuf#107]
I have downloaded a pbf file from http://download.geofabrik.de/europe/germany/berlin.html. And I try to transfer it to json. However it can not be done. Please give me some help. Thank you.
![image](https://user-images.githubusercontent.com/17300744/63424819-cfd0d980-c441-11e9-8aba-d09768217127.png)

**Comment by mourner** [comment]
You're trying to use Geobuf, which is a different format from what Geofabrik provides (OSM PBF).
