### ISSUE TITLE
Question: Why the encode and decode logic?

### ISSUE THREAD

**Issue by 4F2E4A2E** [mapbox/geobuf#116]
Hi there, 

thank you so much for this repo and great work.
I am new to this topic and think I did not understand something essentially here. 

_**Is there no way to design a proto message which will represent a geojson completely and let protoc create the pb files with the generated encode and decode functions?**_

Why do we need the custom logic in the encode and decode js files? What are the limitations I am not getting here?

Any help is much apreciatet. Thank you.

**Comment by 4F2E4A2E** [comment]
@mourner can you help out?

**Comment by mourner** [comment]
We need custom encoding and decoding logic to apply GeoJSON-specific compression algorithms such as delta-encoding coordinates and deduplicating property keys & values, allowing for much compact files. If you were to encode GeoJSON files as is into Protocol Buffers, you would get much bigger file sizes.
