### ISSUE TITLE
Geobuf Format: Rename Type to GeometryType?

### ISSUE THREAD

**Issue by joto** [mapbox/geobuf#31]
I suggest renaming `Type` to `GeometryType` in the `proto` file. `Type` is much too generic a name.

**Comment by tmcw** [comment]
:+1: definitely better to be explicit, and no perf or size affect of switching.

**Comment by artemp** [comment]
Do we want to rename  geobuf2json to geobuf2geojson etc ?

**Comment by mourner** [comment]
@artemp I renamed the binary to `json2geobuf` and `geobuf2json` because of TopoJSON. Are there better names?

**Comment by mourner** [comment]
Now that we ditched TopoJSON, Type can be nested in Geometry message making it more explicit. We still can rename it further though.
