### ISSUE TITLE
Inaccurate floating point arithmetics produce invalid Geometries (non-closed LinearRings)

### ISSUE THREAD

**Issue by artemp** [mapbox/geobuf#35]
### How to reproduce 
Input GeoJSON file created with `ogr2ogr`  (polygon.geojson)
```JSON
{
"type": "FeatureCollection",                                          
"features": [
{ "type": "Feature", "properties": { }, "geometry": { "type": "Polygon", "coordinates": [ [ [ 5425435.733081569895148, 2012689.63544030720368 ], [ 5425333.066045090556145, 2012658.8061882276088 ], [ 5425324.357915714383125, 2012693.518385621719062 ], [ 5425426.5193927353248, 2012720.238697179593146 ], [ 5425435.733081569895148, 2012689.63544030720368 ] ] ] } }
]
}
```
#### 1.
```bash 
json2geobuf data/polygon.geojson > data/polygon.geobuf
```

#### 2. 
```bash 
geobuf2json data/polygon.geobuf 
```

Output:

```JSON
{"type":"FeatureCollection","features":[{"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[5425435.733082,2012689.63544],[5425333.066046,2012658.806188],[5425324.357917,2012693.518385],[5425426.519394,2012720.238697],[5425435.733083,2012689.63544]]]},"properties":{}}]}
```

Note, first and last vertex are not equal

re: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/round

**Comment by mourner** [comment]
Can we solve this simply by throwing out the closing point in each polygon ring? It's assumed to always be equal the first point so we can reconstruct the ring when decoding.

**Comment by artemp** [comment]
@mourner - yes, I think ensuring first and last point of polygon ring are 'equal' would be an easy workaround. 
Better still, lets see if we can get a consensus on enforcing geographic WGS-84 for geobuf as you suggested ( ref : http://www.ietf.org/id/draft-butler-geojson-05.txt) 

@springmeyer @sgillies @tmcw - any thoughts ?

**Comment by tmcw** [comment]
:+1: Yep, I'm in favor of dropping the last coord and resuscitating it on conversion, as well as going WGS84-onlye.

**Comment by springmeyer** [comment]
> Yep, I'm in favor of dropping the last coord and resuscitating it on conversion, as well as going WGS84-only.

Same, :+1:

**Comment by sgillies** [comment]
:+1:  on the last coordinates. By enforcing CRS84 do you mean throwing an error when there's a non-CRS84 CRS object in the GeoJSON?

**Comment by springmeyer** [comment]
> By enforcing CRS84 do you mean throwing an error when there's a non-CRS84 CRS object in the GeoJSON?

Yes, and maybe geojson2geobuf converters could also try to detect and throw on coordinates outside of -360->360/-90->90?

**Comment by artemp** [comment]
@springmeyer - did you mean -180/180 -90/90 ? 

Looks like we all on the same page re:drop last coordinate from linear rings.

Also, it's so tempting to just enforce Lon/Lat WGS84 and avoid CRS tags and undetermined rounding errors in geobuf. Instead of throwing we can handle <Any-CRS> -> WGS84 translation in our tools ? /cc @mourner @sgillies

**Comment by mourner** [comment]
> Instead of throwing we can handle -> WGS84 translation in our tools?

Yes, that's what I had in mind.

**Comment by springmeyer** [comment]
> @springmeyer - did you mean -180/180 -90/90 ?

Well, I said 360 as I understand this may be important as per https://github.com/mapbox/tilelive.js/issues/113.

**Comment by mourner** [comment]
Yeah, there are lots of sources that go beyond -180/180 to solve date line problems in regions like NZ.

**Comment by tschaub** [comment]
@mourner is there anything you could use a hand with before publishing another version with this fix?

**Comment by mourner** [comment]
@tschaub the biggest showstopper currently is redesigning the format to support efficient streaming, see https://github.com/mapbox/geobuf/pull/51 and #37 for several opinions. I'd love more hands on this — I think this is the last thing we want to solve before settling on a stable major version.
