### ISSUE TITLE
Using geobuf in browser, require not found

### ISSUE THREAD

**Issue by chenzhuo8804** [mapbox/geobuf#48]
I am trying to use geobuf in browser 
I ran
 npm run build-min
and got a geobuf-min.js file and have put it in the same folder as html file
I keep getting this error when trying to use the decode function
Uncaught ReferenceError: require is not defined
Probably I am doing some wrong with the browserify part?
Thank you very much

**Comment by mourner** [comment]
Sorry, missed this issue. I assume you figured it out?

**Comment by shanyuk** [comment]
How to solve it?
