### ISSUE TITLE
Browser version cannot be created 

### ISSUE THREAD

**Issue by hrishiballal** [mapbox/geobuf#50]
I downloaded the latest release, ran a npm install and then npm run build-dev (or build-min) and it is erroring out because it cannot find the build-dev or build-min scripts. 

What is the correct way of producing browser js?

**Comment by mourner** [comment]
The scripts are there: https://github.com/mapbox/geobuf/blob/master/package.json#L15-L16
And everything works fine for me. Not sure what the problem is, maybe try updating Node/NPM?
