### ISSUE TITLE
NPM latest points to old version (0.2.4)

### ISSUE THREAD

**Issue by tschaub** [mapbox/geobuf#53]
Would it be possible to `npm publish` the latest?  An updated version would keep people from running into dcodeIO/ProtoBuf.js#164.

Thanks!

**Comment by tmcw** [comment]
Going to wait until @mourner is back from vacay for this - the latest source is a heavily rewritten & improved version of geobuf, and I think he's heading toward a tag before the next publish.

**Comment by mourner** [comment]
I think the problem here is that NPM overwrites default version with the one that was published last. So while all versions were published (up to 1.0.1), there was a patch to the old geobuf (0.2.4) that got published after and now installs instead of the latest one.

**Comment by mourner** [comment]
Should be fine now after:

```
npm tag geobuf@1.0.1 latest
```
