### ISSUE TITLE
Leaflet geobuf example

### ISSUE THREAD

**Issue by ConorCoakley** [mapbox/geobuf#57]
Hi, is it possible to get a leaflet example map, perhaps using the US zip data you mention as an example of how well geobuf performs, and to show how it is implemented?

Thanks,

Conor.

**Comment by mourner** [comment]
It does not need a Leaflet example.

**Comment by baditaflorin** [comment]
Hi @mourner, I`m trying to not use GeoJosn, as I need to load around 50k points. 
I`m researching all over stackoverflow and other websites how to implement geobuf from Postgresql + PostGis to send the data, and Leaflet to load the data.  and use something that will compress size better. But without some examples, I just cannot do the install, so I will either not use this, will try other libraries, or if everything fails, I will consider that the technology is not yet there.

**Comment by baditaflorin** [comment]
Sean, the person that written the RFC for GeoJson recommended Geobuf as one of the alternatives. 
But without examples a lot of folks that are not experimented programers will just not be able to use some of the libraries. 
The only real article that I find related with Geobuf and Leaflet was this https://samc1213.github.io/2019/04/29/rideshare-dataset-getting-started/

Whats the point of having  ST_AsGeobuf in PostGIS if there is not a single blog articles or tutorial on the internet showcasting what you can do with it?
https://postgis.net/docs/ST_AsGeobuf.html

![image](https://user-images.githubusercontent.com/2330999/80293636-87548300-8769-11ea-8816-522a75c4f4bf.png)
