### ISSUE TITLE
proto3 schema

### ISSUE THREAD

**Issue by jeroenooms** [mapbox/geobuf#68]
ProtoBuf v3 was released and supports importing/exporting protobuf data in json format. Would it be possible to device a `.proto` schema that naturally maps to `geojson` data when data is exported?

I know this is quite different from the current system, but it might be useful nevertheless.

**Comment by mourner** [comment]
> ProtoBuf v3 was released and supports importing/exporting protobuf data in json format.

The export is verbose, which will defy the purpose of the Geobuf format. It's also not arbitrary.

I don't think there's anything in v3 that will be very useful in Geobuf — the format revision itself is mostly about minor nuances like default values.
