### ISSUE TITLE
Backward compatibility

### ISSUE THREAD

**Issue by jeroenooms** [mapbox/geobuf#69]
Trying to compile on Ubuntu 14.04 with protobuf 2.4.1 gives:

```
Using libprotoc 2.4.1 from /usr/bin/protoc
geobuf.proto:11:5: Expected "required", "optional", or "repeated".
geobuf.proto:11:21: Missing field number.
geobuf.proto:20:9: Expected "required", "optional", or "repeated".
geobuf.proto:20:23: Missing field number.
geobuf.proto:59:9: Expected "required", "optional", or "repeated".
geobuf.proto:59:26: Missing field number.
```

I suppose this version does not support the `oneof` feature. Is there any way I can modify the `proto` file to work with older versions of protobuf yet still generate the same buffers? Can I simply take out the `oneof` clause?

**Comment by mourner** [comment]
Yes, you would just take out the `oneof` block and add `optional` keywords to each of its fields.

**Comment by jeroenooms** [comment]
Thanks that seems to work.
