### ISSUE TITLE
Property indexes

### ISSUE THREAD

**Issue by jeroen** [mapbox/geobuf#70]
Within the `properties` and `custom_properties` array, the numbers at even indices refer to the position of a key inside `repeated string keys`. But what are the numbers at odd indices for? It seems they are simply sequent integers? Are they redundant?

**Comment by mourner** [comment]
Sorry for a late reply. The even indices refer to the _values_, while odd indices refer to the _keys_. They will look like sequent integers when there's the same set of keys in the same order in every feature, but that's not always the case in GeoJSON, and we have to preserve order and lack of certain keys.
