### ISSUE TITLE
how to streaming geobuf in client?

### ISSUE THREAD

**Issue by hoogw** [mapbox/geobuf#75]
I have a new york queens zoning geojson 163MB, I convert it to geobuf 40MB, great!
But transfer 40MB from server to client browser still feels slow responsive.

Is that possible and how to streaming geobuf? Like oboe.js, it can streaming geojson. 

while you downloading geojson, it parser what already downloaded and out put json object one by one, so I can render json object one by one instead of wait the whole bunk of 163MB completed download. 

How to partially read or parse already downloaded geobuf?

**Comment by stepankuzmin** [comment]
Same question here. I've tried like this

```js
const geobufStream = new Transform({
  objectMode: true,
  writableObjectMode: true,
  transform: (chunk, encoding, callback) =>
    callback(Buffer.from(geobuf.encode(chunk, new Pbf())))
});
```

But it only encodes first chunk (GeoJSON Feature in my case).

**Comment by tmcw** [comment]
Streaming reads and writes are not yet supported: see #37 for the discussion around that part of the specification design.
