### ISSUE TITLE
Slight confusion on sample compression rate table

### ISSUE THREAD

**Issue by donmccurdy** [mapbox/geobuf#81]
In the table from README.md,

file                | normal    | gzipped
------------------- | --------- | --------
us-zips.json 	      | 101.85 MB | 26.67 MB
us-zips.pbf         | 12.24 MB  | 10.48 MB
idaho.json          | 10.92 MB  | 2.57 MB
idaho.pbf           | 1.37 MB   | 1.17 MB

I assume that the *gzipped* column refers to gzipped AND geobuf-encoded, not just uncompressed GeoJSON vs gzipped GeoJSON? If so, it might be helpful to clarify that and maybe include a gzip-only column.

Thanks!

**Comment by mourner** [comment]
You can see what it refers to by looking at the file names — `.json` is GeoJSON, and `.pbf` is Geobuf. I should probably reformat the table to make this clearer.

**Comment by donmccurdy** [comment]
Ahh I read that too quickly. Makes sense, thanks!
